version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradle assemble
  - gradle build
  - gradle jar
  - gradle javadoc

test_script:
  - gradle check

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true
